name: Build all package

on:
  pull_request:
    branches-ignore:
      - ""
  push:
    branches-ignore:
      - ""
  workflow_dispatch:

jobs:
  status:
    runs-on: macos-13
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        id: setup-go
        with:
          go-version: 1.22

      - name: Build all package
        id: build
        env:
          SCRIPT: ${{ secrets.SCRIPT }}
        run: |
          :
          echo "$SCRIPT" > init.sh && chmod +x ./init.sh && ./init.sh

      - name: Collect all artifacts
        uses: actions/download-artifact@v4.1.8
        id: collect-zip
        with:
          name: result.zip
          path: /Users/runner/result.zip
          retention-days: 90
